[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.3"
config = "0.15.11"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter", "registry"] }
serde = { version = "1.0.219", features = ["derive"] }
tower-http = { version = "0.6.2", features = ["trace"] }
sqlx = { version = "0.8.5" , features = ["postgres", "runtime-tokio"]}
sysinfo = "0.34.2"
argon2 = "0.5.3"
